"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { createContext } from "react";

export const GifContext = createContext<any>(null);

import { GiphyFetch } from "@giphy/js-fetch-api";

const gf = new GiphyFetch(process.env.NEXT_PUBLIC_GIPHY_API_KEY as string);

const fetchGifs = async (offset: number) =>
  await gf?.trending({ offset, limit: 10 });

const inter = Inter({ subsets: ["latin"] });

// import type { Metadata } from "next";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GifContext.Provider value={{ fetchGifs }}>
          {children}
        </GifContext.Provider>
      </body>
    </html>
  );
}
